COUNTRIES = [
    ("Algeria", "DZ"),
    ("Angola", "AO"),
    ("Argentina", "AR"),
    ("Australia", "AU"),
    ("Austria", "AT"),
    ("Belgium", "BE"),
    ("Bolivia", "BO"),
    ("Brazil", "BR"),
    ("Bulgaria", "BG"),
    ("Cameroon", "CM"),
    ("Canada", "CA"),
    ("Chile", "CL"),
    ("China", "CN"),
    ("Colombia", "CO"),
    ("Costa Rica", "CR"),
    ("Croatia", "HR"),
    ("Cuba", "CU"),
    ("Czech Republic", "CZ"),
    ("Denmark", "DK"),
    ("Ecuador", "EC"),
    ("Egypt", "EG"),
    ("Finland", "FI"),
    ("France", "FR"),
    ("Germany", "DE"),
    ("Greece", "GR"),
    ("Holy See (Vatican City State)", "VA"),
    ("Hungary", "HU"),
    ("Iceland", "IS"),
    ("India", "IN"),
    ("Indonesia", "ID"),
    ("Iraq", "IQ"),
    ("Ireland", "IE"),
    ("Israel", "IL"),
    ("Italy", "IT"),
    ("Jamaica", "JM"),
    ("Japan", "JP"),
    ("Kazakhstan", "KZ"),
    ("Korea", "KR"),
    ("North Korea", "KP"),
    ("Madagascar", "MG"),
    ("Maldives", "MV"),
    ("Mexico", "MX"),
    ("Morocco", "MA"),
    ("New Zealand", "NZ"),
    ("Norway", "NO"),
    ("Paraguay", "PY"),
    ("Peru", "PE"),
    ("Philippines", "PH"),
    ("Poland", "PL"),
    ("Portugal", "PT"),
    ("Qatar", "QA"),
    ("Russian Federation", "RU"),
    ("Saudi Arabia", "SA"),
    ("Serbia", "RS"),
    ("Singapore", "SG"),
    ("South Africa", "ZA"),
    ("Spain", "ES"),
    ("Sweden", "SE"),
    ("Switzerland", "CH"),
    ("Syrian Arab Republic", "SY"),
    ("Turkey", "TR"),
    ("United Arab Emirates", "AE"),
    ("United Kingdom", "GB"),
    ("United States", "US"),
    ("Uruguay", "UY"),
    ("Venezuela", "VE"),
]
